---
- name: ensure timezone
  shell: |
    timedatectl set-timezone {{ timezone_name }}
    timedatectl show -p Timezone --value
  register: ensured_timezone
  changed_when: timezone_name == timezone.stdout
  when: timezone_name != timezone.stdout
